// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRhCuZqgLzf5VYUMs7gll2LBhGVqIgwzU',
    appId: '1:881088302375:web:366a20fb126121cc06ad02',
    messagingSenderId: '881088302375',
    projectId: 'gausampada-c8a09',
    authDomain: 'gausampada-c8a09.firebaseapp.com',
    storageBucket: 'gausampada-c8a09.firebasestorage.app',
    measurementId: 'G-JXS9RPRC2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuFAsKTok9iao_t7MAPFq_qcm8HFEgQJU',
    appId: '1:881088302375:android:a7f6bcbbe4c9ba8206ad02',
    messagingSenderId: '881088302375',
    projectId: 'gausampada-c8a09',
    storageBucket: 'gausampada-c8a09.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByDavedHr-qbO3ZJ4MM5uE24hvOCWUQM8',
    appId: '1:881088302375:ios:ba27329695cc600c06ad02',
    messagingSenderId: '881088302375',
    projectId: 'gausampada-c8a09',
    storageBucket: 'gausampada-c8a09.firebasestorage.app',
    iosBundleId: 'com.example.gausampada',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByDavedHr-qbO3ZJ4MM5uE24hvOCWUQM8',
    appId: '1:881088302375:ios:ba27329695cc600c06ad02',
    messagingSenderId: '881088302375',
    projectId: 'gausampada-c8a09',
    storageBucket: 'gausampada-c8a09.firebasestorage.app',
    iosBundleId: 'com.example.gausampada',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCRhCuZqgLzf5VYUMs7gll2LBhGVqIgwzU',
    appId: '1:881088302375:web:68b61d28b0e6287206ad02',
    messagingSenderId: '881088302375',
    projectId: 'gausampada-c8a09',
    authDomain: 'gausampada-c8a09.firebaseapp.com',
    storageBucket: 'gausampada-c8a09.firebasestorage.app',
    measurementId: 'G-P9JBXWT111',
  );

}